# Generated by Django 4.2.23 on 2025-08-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceberg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
